menu_items = [["Rekening",
               ("Overzicht rekeningen", "Overzicht rekeningen"),
               ("Importeer afschriften ING", "Rekening - Importeer afschriften ING"),
               ("Connect met ING", "Rekening - Connect met ING")],
              ["Mutaties",
               ("ING", "Mutaties - ING"),
               ("Open2", "File2 - Open2"),
               ("Save2", "File2 - Save2")],
              ["Stambestanden",
               ("Rubrieken", "Stambestanden - Rubrieken"),
               ("Verdelen", "File3 - Open3"),
               ("Save3", "File3 - Save3")],
              ["Budgetten",
               ("Definiëren periodes", "Budgetten - Definiëren budgetperiodes"),
               ("Budgetteren", "Budgetten - Budgetteren"),
               ("Save3", "File3 - Save3")]]